.TH "JProc" "1" "Feb 24, 2013" "jproc 1\&.0"
.SH "NAME"
jproc \- process information for java
.SH "SYNOPSIS"
.LP
jproc subcommand [arguments]
.SH DESCRIPTION
.LP
The jproc utility is used to invoke several demonstrations of accessing
process data from java.
.LP
To see the available subcommands, invoke jproc without any arguments.
