./" SPDX-FileCopyrightText: 2025 Peter Tribble
./" SPDX-License-Identifier: CDDL-1.0
.TH "JPROC" "1" "May 26, 2020"
.SH "NAME"
jproc \- process information for java
.SH "SYNOPSIS"
jproc subcommand [arguments]
.SH DESCRIPTION
The jproc utility is used to invoke several demonstrations of accessing
process data from java.
.LP
To see the available subcommands, invoke jproc without any arguments.
