#!/bin/sh
#
# build jproc
# optionally create the jni header file or run an application
#
# Usage:
#
# ./build
#    Builds all the java classes, and recompiles the native library.
#
# ./build -jni
#    (Re)Creates the jni header file. Only needed if the native interface
#    changes, which it shouldn't very often
#
# ./build -doc
#    Generates the javadoc
#
# ./build clean
#    Removes all the class files, ready for distribution
#
# ./build pmd
#    Runs the pmd static code analysis tool, if it's installed
#
# ./build spotbugs
#    Runs the spotbugs static code analysis tool, if it's installed
#
# ./build packages [deps]
#    Creates SVR4 packages
#
# ./build war
#    Creates a war file to run an XMLRPC server with tomcat
#    See README.SERVER for details of how to run it
#
# If you have the ON build tools installed, then jstyle gets run.
#

PATH=/usr/jdk/instances/jdk1.8.0/bin:$PATH
export PATH

JPDIR=`dirname $0`
LIBDIR=${JPDIR}/lib
ARCHLIBDIR=${LIBDIR}/`/usr/bin/isainfo -k`
JARLIBDIR=${LIBDIR}/java

JSONJAR=${JARLIBDIR}/json-20240303.jar
JINGLEJAR=${JARLIBDIR}/jingle.jar
JUMBLEJAR=${JARLIBDIR}/jumble.jar
JPJAR=${JARLIBDIR}/jproc.jar
JPAPIJAR=${JARLIBDIR}/jproc-api.jar
HTTPJARS=${JARLIBDIR}/httpclient-4.5.14.jar:${JARLIBDIR}/httpcore-4.4.16.jar
REMOTEJARS=${JARLIBDIR}/xmlrpc-common-3.1.3.jar:${JARLIBDIR}/xmlrpc-server-3.1.3.jar:${JARLIBDIR}/xmlrpc-client-3.1.3.jar:${JARLIBDIR}/jmdns-3.5.9.jar
BUILDJARS=${JSONJAR}:${JINGLEJAR}:${JUMBLEJAR}:${REMOTEJARS}:${HTTPJARS}

#
# run
# ./build pmd
# to use this, you must have pmd in your path
#
# new PMD version 7 only has categories, configured in pmd-ruleset.xml
#
PMDRULES="./pmd-ruleset.xml"
PMDCACHE="${HOME}/.pmd/cache.jproc"

case $1 in
jni|-jni)
	javac uk/co/petertribble/jproc/api/NativeJProc.java
	javah -jni uk.co.petertribble.jproc.api.NativeJProc
	exit 0
	;;
doc|-doc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -d javadoc -classpath .:$BUILDJARS uk.co.petertribble.jproc.api uk.co.petertribble.jproc.gui uk.co.petertribble.jproc.demo
	exit 0
	;;
clean|-clean)
	rm -f `find uk/co -name '*.class'`
	rm -f `find . -type f -name '*~'`
	rm -fr javadoc
	rm -f jproc.war
	exit 0
	;;
pmd|-pmd)
	if [ ! -d ${HOME}/.pmd ]; then
	    mkdir -p ${HOME}/.pmd
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R ${PMDRULES} --use-version java-1.8 --aux-classpath $(echo lib/java/* | sed 's= =:=g') 2>/dev/null
	pmd check --cache ${PMDCACHE}.html -d help/*.html  -R category/html/bestpractices.xml 2>/dev/null
	exit 0
	;;
spotbugs)
	#
	# spotbugs works on the class files, so those need to be available
	#
	./build
	spotbugs -auxclasspath $(echo lib/java/* | sed 's= =:=g') uk
	exit 0
	;;
packages)
	sed s:INSTALLED=false:INSTALLED=true: jproc > jproc.installed
	./mkproto i386 $2 > prototype.i386
	./mkproto sparc $2 > prototype.sparc
	pkgmk -d /tmp -f prototype.i386 -r `pwd` TRIBjproc
	pkgtrans -s /tmp /tmp/TRIBjproc-i386.pkg TRIBjproc
	rm -fr /tmp/TRIBjproc
	pkgmk -d /tmp -f prototype.sparc -r `pwd` TRIBjproc
	pkgtrans -s /tmp /tmp/TRIBjproc-sparc.pkg TRIBjproc
	rm -fr /tmp/TRIBjproc
	ls -l /tmp/TRIBjproc-sparc.pkg /tmp/TRIBjproc-i386.pkg
	rm prototype.i386 prototype.sparc
	rm jproc.installed
	rm -f depend
	exit 0
	;;
war)
	mkdir war
	cd war
	mkdir -p WEB-INF/lib
	mkdir -p org/apache/xmlrpc/webserver
	cp -p ../properties/PServer1.properties org/apache/xmlrpc/webserver/XmlRpcServlet.properties
	jar cf WEB-INF/lib/props.jar org
	rm -fr org
	# only copy the jars we need
	cp ../lib/java/jproc.jar ../lib/java/ws* ../lib/java/xmlrpc* ../lib/java/commons-logging* WEB-INF/lib
	cp ../WEB-INF/web.xml WEB-INF
	jar cf ../jproc.war *
	cd ..
	rm -fr war
	exit 0
	;;
esac

XFLAGS="-Xlint -Xlint:-serial"

if [ -x /opt/onbld/bin/jstyle ]; then
	/opt/onbld/bin/jstyle `find uk/co/petertribble -name '*.java'`
fi

javac ${XFLAGS} -classpath .:${BUILDJARS} uk/co/petertribble/jproc/api/*.java uk/co/petertribble/jproc/demo/*.java uk/co/petertribble/jproc/gui/*.java uk/co/petertribble/jproc/server/*.java uk/co/petertribble/jproc/client/*.java uk/co/petertribble/jproc/parse/*.java

#
# compiling 64-bit objects is just plain funky
#
case `isainfo -k` in
amd64)
    cc -Kpic -shared -m64 -I/usr/java/include -I/usr/java/include/solaris -h libproc_jni.so -lproject -o ${ARCHLIBDIR}/libproc_jni.so uk_co_petertribble_jproc_api_NativeJProc.c
    ;;
sparcv9)
    cc -xcode=pic13 -shared -m64 -I/usr/java/include -I/usr/java/include/solaris -h libproc_jni.so -lproject -o ${ARCHLIBDIR}/libproc_jni.so uk_co_petertribble_jproc_api_NativeJProc.c
    ;;
esac

jar -cmf jproc.manifest ${JPJAR} help/*.html help/CDDL.txt properties/*.properties `find uk/co -name '*.class'`

jar -cf ${JPAPIJAR} `find uk/co/petertribble/jproc/api -name '*.class'`
