#!/bin/sh
#
# generate a prototype file for input to pkgmk
#
# feed to pkgmk like so:
#  pkgmk -d /tmp -f tt -r `pwd` TRIBjproc
#

JARDIR=usr/share/jproc
LIBDIR=usr/lib
OWNER="root bin"
SYSOWNER="root sys"
JLIB="libproc_jni.so"

MYARCH=$1
PKGTYPE="standalone"

echo "i pkginfo=./pkginfo.${MYARCH}"

if [ "X$2" = "Xdeps" ]; then
  HCVERS="4.2.3"
  HCPKGVER="423"
  XMLVERS="3.1.3"
  XMLPKGVER="313"
  PKGTYPE="withdeps"
cat > depend <<EOF
P TRIBapache-hc-client-${HCPKGVER}
P TRIBapache-xmlrpc-${XMLPKGVER}
EOF
  echo "i depend=./depend"
fi

case $MYARCH in
i386)
	echo "f none /${LIBDIR}/${JLIB}=lib/i386/${JLIB} 0755 ${OWNER}"
	echo "f none /${LIBDIR}/amd64/${JLIB}=lib/amd64/${JLIB} 0755 ${OWNER}"
	;;
sparc)
	echo "f none /${LIBDIR}/${JLIB}=lib/sparc/${JLIB} 0755 ${OWNER}"
	echo "f none /${LIBDIR}/sparcv9/${JLIB}=lib/sparcv9/${JLIB} 0755 ${OWNER}"
	;;
esac

echo "f none /usr/bin/jproc=jproc.installed 0755 ${OWNER}"
echo "d none /usr/share 0755 ${SYSOWNER}"
echo "d none /usr/share/jproc 0755 ${OWNER}"
echo "d none /usr/share/man 0755 ${OWNER}"
echo "f none /usr/share/man/man1/jproc.1=man1/jproc.1 0644 ${OWNER}"
echo "f none /usr/share/jproc/jproc.xml=./jproc.xml 0644 ${OWNER}"
echo "f none /usr/share/jproc/README=./README 0644 ${OWNER}"

#
# if depending on installed packages, then:
#   commons* http* come from TRIBapache-hc-client-###
#   ws-commons* xmlrpc* come from TRIBapache-xmlrpc-###
#
if [ "X$PKGTYPE" = "Xstandalone" ]; then
  for path in lib/java/*
  do
	pname=`basename $path`
	echo "f none /${JARDIR}/${pname}=${path} 0644 ${OWNER}"
  done
else
  for path in lib/java/commons* lib/java/http*
  do
	pname=`basename $path`
	echo "s none /${JARDIR}/${pname}=../httpcomponents-client-${HCVERS}/${pname}"
  done
  for path in lib/java/jingle.jar lib/java/jproc* lib/java/jumble.jar lib/java/org-json.jar
  do
	pname=`basename $path`
	echo "f none /${JARDIR}/${pname}=${path} 0644 ${OWNER}"
  done
  for path in lib/java/ws-commons* lib/java/xmlrpc*
  do
	pname=`basename $path`
	echo "s none /${JARDIR}/${pname}=../apache-xmlrpc-${XMLVERS}/${pname}"
  done
fi
