/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_petertribble_jproc_api_NativeJProc */

#ifndef _Included_uk_co_petertribble_jproc_api_NativeJProc
#define _Included_uk_co_petertribble_jproc_api_NativeJProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getStatus
 * Signature: (I)Luk/co/petertribble/jproc/api/JProcStatus;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getLwpStatus
 * Signature: (II)Luk/co/petertribble/jproc/api/JProcLwpStatus;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getLwpStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getInfo
 * Signature: (I)Luk/co/petertribble/jproc/api/JProcInfo;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getLwpInfo
 * Signature: (II)Luk/co/petertribble/jproc/api/JProcLwpInfo;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getLwpInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getUsage
 * Signature: (I)Luk/co/petertribble/jproc/api/JProcUsage;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getUsage
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getLwpUsage
 * Signature: (II)Luk/co/petertribble/jproc/api/JProcUsage;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getLwpUsage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getUserName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getUserName
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getUserId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getUserId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getGroupName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getGroupName
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getGroupId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getGroupId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getProjectName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getProjectName
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getProjectId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getProjectId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getZoneName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getZoneName
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    getZoneId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_getZoneId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_petertribble_jproc_api_NativeJProc
 * Method:    cacheids
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_petertribble_jproc_api_NativeJProc_cacheids
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
